# Namespace
apiVersion: v1 
kind: Namespace 
metadata:
  name: nginx-ns
  labels:
    app: nginx-web
    env: dev
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-deploy
  namespace: nginx-ns
  labels: 
    app: nginx-web
    env: dev
spec:
  replicas: 5
  selector:
    matchLabels:  # Corrected from "matachLabels" to "matchLabels"
      app: nginx-web
      env: dev
  template:
    metadata:
      labels:
        app: nginx-web
        env: dev
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
---
# NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-ns
  labels:
    app: nginx-web
    env: dev
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80  # Corrected from "targetport" to "targetPort"
      nodePort: 30080
  selector:
    app: nginx-web
    env: dev
